export type SHero = {
    heroId: number,
    xp: number,
    level: number,
    color: number,
    slot1: number,
    slot2: number,
    slot3: number,
    slot4: number,
    slot5: number,
    slot6: number,
    skill1: number,
    skill2: number,
    skill3: number,
    skill4: number,
    power: number,
    star: number,
}