export const PLAYER_SIZE = 52
export const PLAYER_ACCELERATION_STEADY = 5000
export const PLAYER_ACCELERATION_CHANGE = 1000
export const PLAYER_DRAG = 400
export const PLAYER_DEFAULT_SPEED = 400
export const PLAYER_DEFAULT_HEALTH = 1000
export const PLAYER_TO_PLAYER_DAMAGE = 100
export const PLAYER_BLINK_DISTANCE = 500
export const PLAYER_BLINK_TIMING = 10

export const WORLD_WIDTH = 8000
export const WORLD_HEIGHT = 8000
export const MAX_PLAYER = 10

export const HEALTH_BAR_COLOR_BACKGROUND = 0xffffff
export const HEALTH_BAR_COLOR_LOW = 0xff0000
export const HEALTH_BAR_COLOR_MEDIUM = 0xFFA500
export const HEALTH_BAR_COLOR_HIGH = 0x00ff00

export const HUD_HEIGHT = 60
export const HUD_PADDING = 4
export const HUD_PADDING_INNER = HUD_PADDING / 2
export const HUD_BACKGROUND = 0x1313a8
export const HUD_BACKGROUND_ITEM = 0x000000
export const HUD_SLOT_COLOR_SELECTED =  0x3366E5
export const HUD_SLOT_COLOR_UNSELECTED = 0x5577d5 

export const CONSUMABLE_WIDTH = 24
export const CONSUMABLE_HEIGHT = 24
export const PARALAX_SCROLL_FACTOR = 0.04
